package ecommerce.pos.enumerador;

//ENUMERADOR QUE DEFINE O GÊNERO DE UM PRODUTO
//SERÁ UTILIZADO NAS CLASSES QUE NECESSITAR CATEGORIZAR UM PRODUTO OU MERCADORIA
public enum GeneroProduto {
    COMPONETES, 
    PERIFERICOS, 
    CONECTIVADE, 
    SEGURANCA, 
    AUTOMACAO, 
    MULTIMIDIA, 
    SISTEMA_OPERACIONAL;
}
