package ecommerce.pos.enumerador;

// ENUMERADOR QUE DEFINE O BANCO E SEU CÓDIGO CORRESPONDENTE
//SERÁ UTILIZADO NAS CLASSES QUE NECESSITAR DE DADOS DE ALGUM BANCO.
public enum TipoBanco {
    
    BANCO_DO_BRASIL,
    CAIXA_ECONOMICA_FEDERAL,
    SANTANDER,
    ITAU,
    BRADESCO   
}
